version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/frimps6-5/udacity-way/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  test-job:
    environment:
      test_env: test_env_value
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # Sup Suckas!!

workflows:
  my-custom-workflow:
    jobs:
      - test-job

